var texts = {
  'at_least_2_players_needed': { en: 'You need to name at least two players', cz: '' },
  'player_on_move({1})': { en: 'Currently player {1} is on move', cz: '' },
  'take_cards({1})': { en: 'Take {1}', cz: '' },
  'new_color': { en: 'New color', cz: '' },
  'taken_cards:{1}': { en: 'Taken {1}', cz: '' },
  'skipped_due_a': { en: 'Skipped the round due to A', cz: '' },
  'no_moves_yet': { en: 'No moves done yet', cz: '' },
  'decide_on_move_first': { en: 'Decide about move first', cz: '' },
  '1_card': { en: '1 card', cz: '' },
  '2_4_cards{1}': { en: '{1} cards', cz: '' },
  'more_cards{1}': { en: '{1} cards', cz: '' },
  'game_header': { en: 'MauMau Mobile', cz: '' },
  'player_intro': { en: 'MauMau is game for 2-5 players.', cz: '' },
  'player_1st': { en: 'Player #1', cz: '' },
  'player_2nd': { en: 'Player #2', cz: '' },
  'player_3rd': { en: 'Player #3', cz: '' },
  'player_4th': { en: 'Player #4', cz: '' },
  'player_5th': { en: 'Player #5', cz: '' },
  'start_game_button': { en: 'Start game', cz: '' },
  'title_cards_on_desk': { en: 'Cards on desk', cz: '' },
  'title_select_next_color': { en: 'Select the next color', cz: '' },
  'title_cards_in_hand': { en: 'Cards in your hand', cz: '' },
  'ready_next_button': { en: 'Ready! Move on to next player', cz: '' },
  'title_other_players': { en: 'Other players', cz: '' },
  'next_player_is': { en: 'Next player is', cz: '' },
  'when_ready_click_button': { en: 'When ready, click on button', cz: '' },
  'ready_for_game_button': { en: 'Ready for game', cz: '' },
  'and_winner_is': { en: 'And winner is', cz: '' },
  'celebrate_hint': { en: 'Celebrate a bit and start anoter game', cz: '' },
  'new_game_button': { en: 'New game', cz: '' } 
};
